// Startdaten aus Bewerbungstracker_2026.xlsx - einmaliger Seed-Import in Firebase.
const SEED_APPLICATIONS = [
  {
    "name": "Netempire",
    "interest": "Sehr gerne",
    "website": "Jobs – Netempire Software GmbH",
    "location": "Rösrath",
    "address": "Lüghauser Str. 16, 51503 Rösrath",
    "dateApplied": "2026-02-18",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "SCOOP",
    "interest": "Gerne",
    "website": "Jobs - SCOOP Software",
    "location": "Köln",
    "address": "Eiler Str. 3P, 51107 Köln",
    "dateApplied": "2026-02-25",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "bevutaIT",
    "interest": "Sehr gerne",
    "website": "Unser Team rund um Köln und überall auf der Welt | bevuta IT",
    "location": "Köln",
    "address": "Ettore-Bugatti-Straße 35, 51149 Köln",
    "dateApplied": "2026-02-25",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "mobivention",
    "interest": "Gerne",
    "website": "IT-Dienstleister für App Entwicklung, Web Apps & Backends",
    "location": "Köln",
    "address": "Am bhf 132, 51147 Köln",
    "dateApplied": "2026-02-25",
    "followedUp": "2026-04-15",
    "status": "Nachgefragt",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "MaProTa Gmbh",
    "interest": "Sehr gerne",
    "website": "Karriere - MaProTa GmbH",
    "location": "Rösrath",
    "address": "Lüghauser Str. 16, 51503 Rösrath",
    "dateApplied": "2026-03-11",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "02205-9189170",
    "notes": ""
  },
  {
    "name": "BEWOTEC",
    "interest": "Ja",
    "website": "BEWOTEC Karriere – Jobs & Chancen in der Touristiksoftware",
    "location": "Rösrath",
    "address": "Karl-Schiller-Straße 3, 51503 Rösrath",
    "dateApplied": "2026-03-11",
    "followedUp": "2026-04-15",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "ISIFIVE eG",
    "interest": "Ja",
    "website": "Team - ISIFIVE",
    "location": "Köln",
    "address": "Rösrather Str. 702, 51107 Köln",
    "dateApplied": "2026-03-11",
    "followedUp": "2026-04-15",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "PRODATEC",
    "interest": "Ja",
    "website": "https://www.prodatec.de/karriere",
    "location": "Bergisch Gladbach",
    "address": "Burggraben 7, 51429 Bergisch Gladbach",
    "dateApplied": "2026-03-11",
    "followedUp": "2026-04-15",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "INNEO",
    "interest": "Gerne",
    "website": "https://jobs.inneo.com/stellenangebote.html",
    "location": "Köln",
    "address": "Hansestraße 87, 51149 Köln",
    "dateApplied": "2026-03-11",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "REWE Digital",
    "interest": "Gerne",
    "website": "https://www.rewe-digital.com/de/jobs?location=K%C3%B6ln%2C%20Deutschland&range=25&sort=distance&city[]=K%C3%B6ln&page=1",
    "location": "Köln",
    "address": "Humboldtstraße 140-144, 51149 Köln",
    "dateApplied": "2026-03-11",
    "followedUp": "2026-04-15",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "CLOUSALE",
    "interest": "Joa",
    "website": "ClouSale: Jobs",
    "location": "Rösrath",
    "address": "Hauptstraße 65-67, 51503 Rösrath",
    "dateApplied": "2026-03-25",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Ditcon GmbH",
    "interest": "Joa",
    "website": "https://www.ditcon.de/",
    "location": "Köln",
    "address": "Fuggerstraße 26, 51149 Köln",
    "dateApplied": "2026-04-01",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "FISI 02203 89860",
    "notes": ""
  },
  {
    "name": "Netrix IT works",
    "interest": "Gerne",
    "website": "https://www.netrix-it.de/karriere/",
    "location": "Köln",
    "address": "Hansestraße 97, 51149 Köln",
    "dateApplied": "2026-04-01",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "FISI",
    "notes": ""
  },
  {
    "name": "incs",
    "interest": "Joa",
    "website": "https://www.incs.org/ueber-uns/",
    "location": "Köln",
    "address": "Edmund-Rumpler-Straße 6A, 51149 Köln",
    "dateApplied": "2026-04-01",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "ableX GmbH",
    "interest": "Joa",
    "website": "Q&A | ableX Data Solutions",
    "location": "Rösrath",
    "address": "Karl-Schiller-Str. 1, 51503 Rösrath",
    "dateApplied": "2026-04-01",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "02205-9499950",
    "notes": ""
  },
  {
    "name": "CGI",
    "interest": "Ja",
    "website": "Frequently Asked Questions (FAQ) | CGI.com",
    "location": "Köln",
    "address": "Ettore-Bugatti-Straße 6-14, 51149 Köln",
    "dateApplied": "2026-04-01",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "DerGrünePunkt",
    "interest": "Gerne",
    "website": "Karriere | Grüner Punkt",
    "location": "Köln",
    "address": "Edmund-Rumpler-Straße 7, 51149 Köln",
    "dateApplied": "2026-04-01",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "It intouch",
    "interest": "Joa",
    "website": "Karriere - Jobs als Mobile Developer bei IT intouch",
    "location": "Bergisch Gladbach",
    "address": "Lustheide 85, 51427 Bergisch Gladbach",
    "dateApplied": "2026-04-15",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "ED Computer & Design GmbH & Co. KG",
    "interest": "Joa",
    "website": "https://www.edcud.de/systemhaus-dienstleistungen",
    "location": "Köln",
    "address": "Lina-Bommer-Weg 4, 51149 Köln",
    "dateApplied": "2026-04-15",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "CBS University of Applied Sciences",
    "interest": "Ja",
    "website": "https://www.cbs.de/ueber-uns/karriere-an-der-cbs/ausbildung-traineeship#traineeship",
    "location": "Köln-Rodenkirchen",
    "address": "Bahnstraße 6-8 50996 Köln",
    "dateApplied": "2026-04-15",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "CONVOTIS",
    "interest": "Ja",
    "website": "https://www.convotis.com/karriere/",
    "location": "Bergisch Gladbach",
    "address": "Heinz-Fröling-Straße 15",
    "dateApplied": "2026-04-22",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "HEES",
    "interest": "Ja",
    "website": "https://hees.de/karriere/initiativbewerbung/",
    "location": "Lohmar",
    "address": "Hauptstraße 1b, 53797 Lohmar",
    "dateApplied": "2026-04-22",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Loco-Soft",
    "interest": "Ja",
    "website": "https://loco-soft.de/kontakt",
    "location": "Lindlar",
    "address": "Schlosserstraße 33 | D-51789 Lindlar",
    "dateApplied": "2026-04-22",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "WARETRACKS",
    "interest": "",
    "website": "https://www.waretracks.com/",
    "location": "Köln",
    "address": "August-Horch-Straße 17, 51149 Köln",
    "dateApplied": "2026-04-22",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Novum-RGI",
    "interest": "Gerne",
    "website": "https://www.novum-rgi.com/contacts/",
    "location": "Köln",
    "address": "Durchhäuserhof 65, 51107 Köln",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "genDis solution",
    "interest": "Joa",
    "website": "https://www.gendis.de/",
    "location": "Bergisch Gladbach",
    "address": "Schloßstraße 20, 51429 Bergisch Gladbach",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "Gibt es vermutlich nicht mehr",
    "notes": ""
  },
  {
    "name": "Praxcon",
    "interest": "Ja",
    "website": "https://www.praxcon.de/",
    "location": "Bergisch Gladbach",
    "address": "Schau Ins Land 13, 51429 Bergisch Gladbach",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "kompaktwerk GmbH",
    "interest": "Eher nicht",
    "website": "https://www.kompaktwerk.de/wir-sind-kompaktwerk/",
    "location": "Bergisch Gladbach",
    "address": "Sattlerweg 12 b, 51429 Bergisch Gladbach",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "TecAlliance",
    "interest": "Ja",
    "website": "https://career.tecalliance.net/jobs?split_view=true&query=&location=Cologne",
    "location": "Köln",
    "address": "Edmund-Rumpler-Straße 5, 51149 Köln",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Atos",
    "interest": "Ja",
    "website": "https://atos.net/de/join-us?city=118&country=DE",
    "location": "Köln",
    "address": "Von-der-Wettern-Straße 27, 51149 Köln",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Eulen-IT",
    "interest": "Joa",
    "website": "https://www.eulen-it.de/karriere#dataItem-lkmqqnjt",
    "location": "Untereschbach",
    "address": "Brodhausen 1, 51491 Overath",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "bewerbung@eulen-it.de",
    "notes": ""
  },
  {
    "name": "Syntriq GmbH",
    "interest": "",
    "website": "https://syntriq.de/karriere",
    "location": "Köln",
    "address": "Frankfurter Str. 720/726, 51145 Köln",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "COPA-DATA",
    "interest": "",
    "website": "https://www.copadata.com/de/karriere/",
    "location": "Köln",
    "address": "Von-der-Wettern-Straße 27, 51149 Köln",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "jobs-cdde@copadata.com",
    "notes": ""
  },
  {
    "name": "InTradeSys GmbH",
    "interest": "",
    "website": "https://www.intradesys.com/jobs",
    "location": "Köln",
    "address": "Dillenburger Str. 75, 51105 Köln",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "menten GmbH",
    "interest": "",
    "website": "https://stellenportal.menten.com/de",
    "location": "Bergisch Gladbach",
    "address": "An d. Gohrsmühle 25, 51465 Bergisch Gladbach",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "AB-Informatik GmbH, IT-Systemhaus Siegburg",
    "interest": "",
    "website": "https://www.ab-informatik.net/",
    "location": "Siegburg",
    "address": "Am Turm 26, 53721 Siegburg",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "IT-Center Engels",
    "interest": "",
    "website": "https://www.itc-engels.de/impressum",
    "location": "Troisdorf",
    "address": "Heidegraben 4a, 53842 Troisdorf",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "RA-MICRO Vertriebs GmbH Köln",
    "interest": "",
    "website": "https://ra-micro-koeln.de/",
    "location": "Bergisch Gladbach",
    "address": "Auf d. Kaule 23, 51427 Bergisch Gladbach",
    "dateApplied": "2026-04-29",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Schönhofer Sales and Engineering GmbH",
    "interest": "",
    "website": "https://www.schoenhofer.de/unternehmen/jobs/studierende",
    "location": "Siegburg",
    "address": "Lindenstraße 92, 53721 Siegburg",
    "dateApplied": "2026-05-06",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "Melanie Krieger",
    "notes": ""
  },
  {
    "name": "VANTAiO GmbH & Co. KG",
    "interest": "",
    "website": "https://www.vantaio.com/impressum",
    "location": "Siegburg",
    "address": "Am Turm 36, 53721 Siegburg",
    "dateApplied": "2026-05-06",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "360 Consulting GmbH",
    "interest": "",
    "website": "https://www.360-consulting.de/",
    "location": "Köln",
    "address": "Zollstockgürtel 65, 50969 Köln",
    "dateApplied": "2026-05-06",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "Frau Lisa SchuppeliusTel.: +49 (221) 99783106-33",
    "notes": ""
  },
  {
    "name": "SoCura",
    "interest": "",
    "website": "https://www.socura.de/karriere/bei-der-socura-arbeiten/stellenangebote/",
    "location": "Köln",
    "address": "Kaltenbornweg 3, 50679 Köln",
    "dateApplied": "2026-05-08",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "SB Entwicklung GmbH",
    "interest": "",
    "website": "https://sb-e.de/ueber-uns/#karriere",
    "location": "",
    "address": "Mülheimer Str. 20, 53840 Troisdorf",
    "dateApplied": "2026-05-09",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "jobs@sb-e.de",
    "notes": ""
  },
  {
    "name": "ECKD GmbH",
    "interest": "",
    "website": "https://eckd.de/standorte/#koeln",
    "location": "Köln",
    "address": "Herzogstraße 32, 50667 Köln",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "Frau Rabe",
    "notes": ""
  },
  {
    "name": "HTPS Solutions",
    "interest": "",
    "website": "https://htps-solutions.de/impressum/",
    "location": "Neunkirchen-Seelscheid",
    "address": "Elsschlade 9, 53819 Neunkirchen-Seelscheid",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Demic Datentechnik GmbH",
    "interest": "",
    "website": "https://www.demic-datentechnik.de/unternehmen/jobs-und-karriere",
    "location": "Neunkirchen-Seelscheid",
    "address": "Ohlenhohnstraße 48, 53819 Neunkirchen-Seelscheid",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "JOLA",
    "interest": "",
    "website": "https://www.jola.de/jobs",
    "location": "Rösrath",
    "address": "Ludwig-Erhard-Straße 7, 51503 Rösrath",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Förderturm Agentur GmbH",
    "interest": "",
    "website": "https://www.foerderturm-agentur.de/impressum/",
    "location": "Rösrath",
    "address": "Hauptstraße 226, 51503 Rösrath",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Systemhaus Kolb GmbH",
    "interest": "",
    "website": "https://systemhaus-kolb.de/karriere/",
    "location": "Kürten",
    "address": "Kölner Str. 215, 51515 Kürten",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "bewerbung@sh-kolb.de",
    "notes": ""
  },
  {
    "name": "plusserver GmbH",
    "interest": "",
    "website": "https://karriere.plusserver.com/Initiativbewerbung-Quereinsteiger-mwd-de-f900.html",
    "location": "Köln",
    "address": "Welserstraße 14, 51149 Köln",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "LVR-InfoKom",
    "interest": "",
    "website": "https://www.lvr.de/infokom/karriere/ausbildung-und-studium/",
    "location": "Köln",
    "address": "Hermann-Pünder-Str. 1, 50679 Köln",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "identpro Systems GmbH",
    "interest": "",
    "website": "https://identpro.de/jobs-und-karriere/#bewerbung",
    "location": "Troisdorf",
    "address": "Camp-Spich-Straße 4, 53842 Troisdorf, Germany",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "CIDEON Software & Services GmbH & Co. KG",
    "interest": "",
    "website": "https://www.cideon.de/unternehmen/karriere/",
    "location": "Troisdorf",
    "address": "Frankfurter Straße 35, 53840 Troisdorf",
    "dateApplied": "2026-05-13",
    "followedUp": "",
    "status": "Absage",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Healex GmbH",
    "interest": "",
    "website": "https://healex.systems/kontakt/",
    "location": "Köln",
    "address": "Sophienstraße 3, 51149 Köln",
    "dateApplied": "2026-05-20",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "Agheera",
    "interest": "Ja",
    "website": "https://www.agheera.com/privacy-notice",
    "location": "Köln",
    "address": "August-Horch-Straße 5, 51149 Köln",
    "dateApplied": "",
    "followedUp": "",
    "status": "Kein Fit",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "AOK",
    "interest": "Joa",
    "website": "Intitiativbewerbung bei der Krankenkasse | AOK Karriere",
    "location": "Köln",
    "address": "Lina-Bommer-Weg 9, 51149 Köln",
    "dateApplied": "",
    "followedUp": "",
    "status": "Kein Fit",
    "result": "",
    "contact": "",
    "notes": ""
  },
  {
    "name": "oxalis Individualsoftware GmbH",
    "interest": "",
    "website": "https://oxalis.de/de/#contact",
    "location": "Köln",
    "address": "Dülkenstraße, 51143 Köln",
    "dateApplied": "2026-05-20",
    "followedUp": "",
    "status": "Beworben",
    "result": "",
    "contact": "",
    "notes": ""
  }
];

const SEED_PIPELINE = [
  {
    "name": "lise GmbH",
    "address": "Butzweilerhof-Allee 2 50829 Köln-Ossendorf",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Individuelle Softwareentwicklung, über 100 Mitarbeitende, 5× „Great Place to Work\" ausgezeichnet (zuletzt 2026 Platz 8) | .NET, SharePoint, DevOps, KI – IHK-Ausbildungsbetrieb seit 2013"
  },
  {
    "name": "ifaktor GmbH",
    "address": "Bonner Str. 324 50968 Köln-Bayenthal",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "IT-Systemhaus seit über 25 Jahren, Fokus KMU, zertifizierter IHK-Ausbildungsbetrieb | ERP/xRM (MS Dynamics), DMS, Cloud, IT-Sicherheit"
  },
  {
    "name": "Webrunners GmbH",
    "address": "Von-Werth-Str. 37 50670 Köln-Innenstadt",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Agentur für individuelle Softwareentwicklung & Webanwendungen, ca. 15 Jahre am Markt | Django/Python, TYPO3, ERP-Schnittstellen – Praktika in Webentwicklung möglich"
  },
  {
    "name": "elancer-team GmbH",
    "address": "Widdersdorfer Str. 188 50825 Köln-Ehrenfeld",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Webagentur, 11–50 Mitarbeitende, klassische Agenturstruktur | WordPress, Ruby on Rails, Individualsoftware, App-Entwicklung"
  },
  {
    "name": "milkycode GmbH",
    "address": "Osterather Str. 7 50739 Köln-Longerich",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Internetagentur mit Fokus auf E-Commerce-Lösungen für den Mittelstand | Magento, Shopware, WooCommerce, PHP/Laravel/Symfony/VueJS"
  },
  {
    "name": "Explicatis GmbH",
    "address": "Max-Planck-Str. 6–8 50858 Köln-Junkersdorf",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Softwareentwicklung & IT-Beratung, dreimal Deloitte „Technology Fast50 Award\", eigene Produkte (z. B. Custable) | IoT-Plattformen, Cloud-Native, Mobile Apps – Praktika in Web/Mobile"
  },
  {
    "name": "REWE digital GmbH",
    "address": "Humboldtstr. 140–144 51149 Köln-Porz",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "IT-Tochter der REWE Group, einer der größten IT-Arbeitgeber im deutschen Handel | Java, Kotlin, Python, Spring, Angular, Kafka – jährliche FiAe-Ausbildung"
  },
  {
    "name": "business//acts GmbH",
    "address": "Schanzenstr. 7a 51063 Köln-Mülheim",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "CRM-/ECM-Softwarehersteller, eigenes Produkt „sellify\", ca. 20 Mitarbeitende | CRM-Entwicklung, ECM – Initiativbewerbung für Praktikum empfohlen"
  },
  {
    "name": "Werusys GmbH & Co. KG",
    "address": "Kaiser-Wilhelm-Ring 40 50672 Köln (Amtssitz: Morsestr. 4, 50769 Köln)",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "IT-Dienstleister für Prozessindustrie, Teil der Amitec-Gruppe | MES, Energiemanagement, AVEVA PI, eigenes Produkt SynergyVision MES"
  },
  {
    "name": "Saticon GmbH",
    "address": "Köln (Innenstadt)",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Webagentur mit Fokus auf Softwareentwicklung und Online-Marketing | Webentwicklung, Webanwendungen, SEO"
  },
  {
    "name": "Devside GmbH",
    "address": "Köln (HRB 94897)",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Prozessorientierter Softwareentwickler und App-Dienstleister | Softwareentwicklung, App-Entwicklung"
  },
  {
    "name": "inch-media GmbH",
    "address": "Braunsberger Feld 12 51429 Bergisch Gladbach-Herkenrath",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "IT-Systemhaus und Webagentur für KMU, 5–9 Mitarbeitende | Webentwicklung, IT-Security – Praktika via Initiativbewerbung"
  },
  {
    "name": "SP softwarepartner GmbH",
    "address": "Hauptstr. 278 51503 Rösrath-Hoffnungsthal",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Standard- und Individualsoftware für den Mittelstand, Auftragsentwicklung | Consulting, Coaching, Individualsoftware"
  },
  {
    "name": "Sehen-Design e. K.",
    "address": "Rösrath",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Agentur für Windows-Softwareentwicklung, Einzelunternehmen | C#, Delphi, Windows-Anwendungen"
  },
  {
    "name": "tronet GmbH",
    "address": "Klevstr. 4 53840 Troisdorf",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Internet-/Webagentur und Hostingprovider – FiAe-Ausbildung explizit ausgeschrieben | TYPO3, OXID eShop, Web-Anwendungen, Online-Shops, Portale"
  },
  {
    "name": "Rohde & Schwarz Sankt Augustin",
    "address": "Mühlenweg 27 53757 Sankt Augustin",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Hochtechnologie-Konzern (Mess-, Funk-, Cyber-Security-Lösungen), weltweit tätig | FiAe-Ausbildung Start 01.01.2026 am Standort Siegburg"
  },
  {
    "name": "Campus Computersysteme / citadelle.systems",
    "address": "Mottmannstr. 5A 53842 Troisdorf-Oberlar",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "IT-Systemhaus für virtuelle Infrastruktur, Service-Provider-Platz 1 Deutschland 2025 | Cloud, Virtualisierung, IT-Infrastruktur"
  },
  {
    "name": "Cideon Software & Services",
    "address": "Standort Troisdorf",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "IT-Lösungen für Engineering-/Industrieunternehmen | SAP, Cloud, Digital Transformation"
  },
  {
    "name": "Fraunhofer IAIS Sankt Augustin",
    "address": "Schloss Birlinghoven 53757 Sankt Augustin",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Forschungsinstitut für KI, Machine Learning und Big Data, ca. 350 Mitarbeitende | KI, Data Science – regelmäßige Praktika in Anwendungsentwicklung"
  },
  {
    "name": "Currenta GmbH & Co. OHG",
    "address": "Kaiser-Wilhelm-Allee 80 51373 Leverkusen (Chempark)",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Chempark-Betreiber, ca. 5.300 Mitarbeitende inkl. Töchter, eigene IT-Abteilung | Java, C#, Python, Datenbanken – FiAe-Ausbildung ab 01.09.2026 (1.204–1.389 €/Mon.)"
  },
  {
    "name": "Pronova BKK",
    "address": "Horst-Henning-Platz 1 51373 Leverkusen",
    "interest": "",
    "status": "Neu",
    "deadline": "",
    "notes": "Gesetzliche Krankenkasse mit eigener Softwareentwicklung | Versicherungssoftware – FiAe-Ausbildung ab 01.08.2026"
  }
];
